// <auto-generated />
using CRUD_Caminhoes.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUD_Caminhoes.Migrations
{
    [DbContext(typeof(TrucksContext))]
    [Migration("20220517132903_InicialCreate2")]
    partial class InicialCreate2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRUD_Caminhoes.Models.Trucks", b =>
                {
                    b.Property<int>("truckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("truckCreationDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("truckDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("truckName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("truckId");

                    b.ToTable("Trucks");
                });
#pragma warning restore 612, 618
        }
    }
}
